name: ci
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_SEPOLIA_RPC_URL: "https://sepolia.base.org" 
    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python3 -V
          pip install --disable-pip-version-check --no-cache-dir eth-abi

      - name: Cache lib
        uses: actions/cache@v4
        with:
          path: lib
          key: lib-${{ runner.os }}-${{ hashFiles('**/foundry.toml', '**/.gitmodules') }}

      - name: Install deps
        run: forge install --no-git

      - name: Build
        env:
          BASE_SEPOLIA_RPC_URL: ${{ env.BASE_SEPOLIA_RPC_URL }}
        run: |
          echo "BASE_SEPOLIA_RPC_URL=$BASE_SEPOLIA_RPC_URL"
          forge build

      - name: Test
        env:
          BASE_SEPOLIA_RPC_URL: ${{ env.BASE_SEPOLIA_RPC_URL }}
        run: forge test -vvv --ffi


