name: Slither Analysis
# Config File for Public Github Repos
## Private Github needs External Action support, this will not work in Private Github
on:
  # Only run this action on pushes / pull requests to main branch
  push:
    branches: [ main, slither-action ]
  pull_request:
    branches: [ main, slither-action ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Slither
        uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8 # v0.4.0
        id: slither
        # continue-on-error: true
        with:
          sarif: results.sarif
          # Don't fail so that SARIF step still works
          fail-on: none
          # advanced: this can be set by Slither config file by using the next line instead
          # fail-on: config

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

# Set GH_TOKEN permissions to be as restricted as possible
# security-events must be set to write for the SARIF upload step
permissions:
  security-events: write
  contents: read
  actions: read